# the input file or directory, endswith fastq or fastq.gz or fq or fq.gz
#1. directory
#   1). a directory that contains sub directorys, and there are ont reads in the sub diretorys, e.g. the fastq_pass that contains some barcode directorys
#   2). a directory that contains directly fastqs. These fastqs may be many paired ngs data or some ont fastqs just like the barcode in the fastq_pass
#2. file, a fastq file of merged ont data
#3. two files separated by one comma, this means input is a paired ngs reads. The former is read1 and the later is read2
input_fastq: ""

# the primer bed file, if specified, trim_bases will be ignored. else the raw bam will be trimmed depended on the primer positions
primer_bed: ""

# if no primer bed file, the raw fastq will be trimmed {trim_bases} base both of the ends
trim_bases: 20

# if read length is less than {min_read_len}, this read will be dropped
min_read_len: 300

# if read length is greater than {max_read_len}, this read will be dropped, 0 means no limitation
max_read_len: 1600

# if read qual is less than {min_read_qual}, this read will be dropped
min_read_qual: 9

# if read map qual is less than {min_mapq}, this align will be dropped from bam
min_mapq: 40


# analysis_name, default test001
# the pipeline will create a directory named {analysis_name} and if two or more barcode samples in the input_fastq directory,
# then the directory named sample will be created under the {analysis_name}, the dir structure will be like this:

# analysis_name    -----------> the outer directory
#    barcode01     -----------> the first inner directory
#    barcode02     -----------> the second inner directory
#    barcode03     -----------> the third inner directory
#    barcode..     -----------> the 4th
#    barcode..     -----------> the 5th
#    barcode..     -----------> the 6th
#  .....................................
# if just one sample was used, the dir structure will be like this:
# analysis_name    -----------> the outer directory
#    analysis_name -----------> just one inner directory
analysis_name: "test001"

# what sample was analysed, default sars-cov-2
what_sample: "sars-cov-2"

# the medaka model
model: "r941_min_hac_g507"

# the min depth in vcf, if the dp is less than {min_dp}, this position will be N
min_dp: 20

# the min qual of variant quality, if the QUAL is less than {min_qual}, the position will be N
min_qual: 40

# for het site,
# if het_set == "more", this position will be the allele whose depth is bigger;
# elif het_set == "N", this position will be N;
# default more
# this para will be not USED in this pipelline. It is provided for potential future upgrade
het_site: "more"

# the min overlap between alignment with primers' insert region.
# for RAD or RBK kit, this parameter should be 400;
# for LSK 400 amplicon, it should be 200;
# for LSK 1200 amplicon, it should be 800;
# default 300;
min_overlap: 300

# for pass_fastq directory, if the fastq files number in a barcode directory is less than this number,
# this directory will be ignored, because some reads maight be assigned wrong barcode
files_per_bar: 3



